name: Format VOSTD (PhaseII) Code

on:
  push:
    branches:
      - phaseII/verified
  pull_request:
    branches:
      - phaseII/verified
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'phaseII/verified'

jobs:
  format-check:
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y build-essential unzip pkg-config libssl-dev llvm

      - name: Run dv bootstrap
        run: cargo dv bootstrap

      - name: Run dv fmt
        run: make fmt

      - name: Check for formatting changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Run 'make fmt'."
            git diff
            exit 1
          fi